### ISSUE TITLE
Add stack trace support to spark errors

### ISSUE THREAD

**Issue by mathiasschw-db** [apache/spark-connect-go#63]
Example stack trace:

    errors_test.go:56: [sparkerror] Error Type: connection error
        Error Cause: assert.AnError general error for testing
        /Users/mathias.schwarz/spark-connect-go/spark/sparkerrors/errors_test.go:54 (0x104ff9f51)
        	TestStackTracePrint: err := WithType(assert.AnError, ConnectionError)
        /Users/mathias.schwarz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.darwin-arm64/src/testing/testing.go:1689 (0x104eb1d9c)
        	tRunner: fn(t)
        /Users/mathias.schwarz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.darwin-arm64/src/runtime/asm_arm64.s:1222 (0x104e34aa4)
        	goexit: MOVD	R0, R0	// NOP

**Comment by grundprinzip** [comment]
Thanks for your contribution!
